version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    groups:
      gomod-packages:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    groups:
      docker-packages:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*" # local actions are not updated by default, see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    ignore:
      - dependency-name: "codecov/codecov-action"
    groups:
      gh-actions-packages:
        patterns:
          - "*"
