name: trivy-image
description: 'Run Trivy on image'
inputs:
  image:
    description: 'Image name'
    required: true
  registry:
    description: 'Registry to login to pull image, e.g. "ghcr.io" for GHCR, leave empty if image is public'
    required: false
    default: ''
  repo_owner:
    description: 'Name of repository owner, e.g. "github.repository_owner" for ghcr.io'
    required: false
  repo_token:
    description: 'Access token for repository owner, e.g. "secrets.GITHUB_TOKEN" for ghcr.io'
    required: false
  output:
    description: 'Trivy output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
    required: false
runs:
  using: "composite"
  steps:
    - name: Login with registry
      if: inputs.registry != ''
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.repo_owner }}
        password: ${{ inputs.repo_token }}
    - name: Create reports folder
      run: |
        mkdir reports
      shell: sh
    - name: Run Trivy on image
      if: inputs.output == 'sarif'
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
      with:
        image-ref: ${{ inputs.image }}
        scan-type: "image"
        format: 'sarif'
        output: 'reports/trivy-vuln-results.sarif'
      env:
        TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db # Workaround for https://github.com/aquasecurity/trivy-action/issues/389
        TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db # Workaround for https://github.com/aquasecurity/trivy-action/issues/389
    - name: Run Trivy on image
      if: inputs.output == 'table'
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
      with:
        image-ref: ${{ inputs.image }}
        scan-type: "image"
        exit-code: 1
        format: 'table'
      env:
        TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db # Workaround for https://github.com/aquasecurity/trivy-action/issues/389
        TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db # Workaround for https://github.com/aquasecurity/trivy-action/issues/389
    - name: Upload
      if: inputs.output == 'sarif'
      uses: github/codeql-action/upload-sarif@f09c1c0a94de965c15400f5634aa42fac8fb8f88 # v3.27.5
      with:
        sarif_file: 'reports'
