name: trivy-config
description: 'Run Trivy on config'
inputs:
  output:
    description: 'Trivy output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
    required: false
runs:
  using: "composite"
  steps:
    - name: Create reports folder
      run: |
        mkdir reports
      shell: bash
    - name: Render Helm charts
      run: |
        mkdir deployment
        helm template charts/connaisseur > deployment/deployment.yaml
      shell: bash
    - name: Scan deployment.yaml
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
      if: inputs.output == 'table'
      with:
        scan-type: "config"
        scan-ref: "deployment"
        format: 'table'
    - name: Scan Dockerfiles
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
      if: inputs.output == 'table'
      with:
        scan-type: "config"
        scan-ref: "build"
        format: 'table'
    - name: Scan deployment.yaml
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
      if: inputs.output == 'sarif'
      with:
        scan-type: "config"
        scan-ref: "deployment"
        format: 'sarif'
        output: 'reports/trivy-k8s-results.sarif'
    - name: Scan Dockerfiles
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # v0.29.0
      if: inputs.output == 'sarif'
      with:
        scan-type: "config"
        scan-ref: "build"
        format: 'sarif'
        output: 'reports/trivy-docker-results.sarif'
    - name: Upload
      uses: github/codeql-action/upload-sarif@f09c1c0a94de965c15400f5634aa42fac8fb8f88 # v3.27.5
      if: inputs.output == 'sarif'
      with:
        sarif_file: 'reports'
