name: Integration test
description: |
  Run integration tests on a k3s cluster.
inputs:
  registry:
    description: "Docker registry to pull the image from"
    required: true
  username:
    description: "Username for the Docker registry"
    required: true
  image:
    description: "Image to pull from the registry"
    required: true
  tag:
    description: "Tag of the image to pull"
    required: true
  test:
    description: "Test to run"
    required: true
  alerting_ip:
    description: "IP address of the alerting service"
    required: true

runs:
  using: composite
  steps:
    - name: Run test
      run: |
        if [ "${{ inputs.test }}" == "self-hosted-notary" ]; then
          kubectl wait --for=condition=ready pod -l app=notary-server --timeout=60s
          sleep 15 # pod being ready isn't enough for port-forwarding to succeed, so we wait a bit
          kubectl port-forward services/notary-server 4443:4443 &
          sleep 5
        fi
        bash test/integration/main.sh "${{ inputs.test }}"
      env:
        ALERTING_ENDPOINT_IP: ${{ inputs.alerting_ip }}
      shell: bash
    - name: Display Connaisseur configuration
      if: always()
      run: |
        out=$(yq e '... comments=""' charts/connaisseur/values.yaml)
        echo "::group::values.yaml"
        echo "${out}" | yq
        echo "::endgroup::"
        echo "<details><summary>values.yaml</summary>" >> ${GITHUB_STEP_SUMMARY}
        echo "<pre lang=\"yaml\"><code>${out}</code></pre>" >> ${GITHUB_STEP_SUMMARY}
        echo "</details>" >> ${GITHUB_STEP_SUMMARY}
      shell: bash
    - name: Display k8s state if integration test failed
      if: failure()
      run: |
        deploy_out=$(kubectl describe deployments.apps -n connaisseur -lapp.kubernetes.io/name=connaisseur)
        if [ -n "${deploy_out}" ]; then
          echo "${deploy_out}"
          echo "<details><summary>connaisseur deployment</summary>" >> ${GITHUB_STEP_SUMMARY}
          echo "<pre lang=\"yaml\"><code>${deploy_out}</code></pre>" >> ${GITHUB_STEP_SUMMARY}
          echo "</details>" >> ${GITHUB_STEP_SUMMARY}
        fi

        pod_out=$(kubectl describe pods -n connaisseur -lapp.kubernetes.io/name=connaisseur)
        if [ -n "${pod_out}" ]; then
          echo "${pod_out}"
          echo "<details><summary>connaisseur pods</summary>" >> ${GITHUB_STEP_SUMMARY}
          echo "<pre lang=\"yaml\"><code>${pod_out}</code></pre>" >> ${GITHUB_STEP_SUMMARY}
          echo "</details>" >> ${GITHUB_STEP_SUMMARY}
        fi
      shell: bash
    - name: Display logs if integration test failed
      if: failure()
      run: |
        logs_out=$(kubectl logs -n connaisseur -lapp.kubernetes.io/name=connaisseur --prefix=true --tail=-1)
        if [ -n "${logs_out}" ]; then
          echo "${logs_out}"
          echo "<details><summary>connaisseur logs</summary>" >> ${GITHUB_STEP_SUMMARY}
          echo "<pre lang=\"bash\"><code>${logs_out}</code></pre>" >> ${GITHUB_STEP_SUMMARY}
          echo "</details>" >> ${GITHUB_STEP_SUMMARY}
        fi
      shell: bash
