name: notary-service
description: 'Sets up a notary service (signer or server)'
inputs:
  service:
    description: "Which kind of service is to be started (signer or server)"
    required: true
  port_map:
    description: "The port mapping for the service container"
    required: true
  add_host:
    description: "What additional hosts to add to the service"
    required: false
outputs:
  ip:
    description: "IP address of the notary service"
    value: ${{ steps.get_service_ip.outputs.service_ip }}
runs:
  using: composite
  steps:
    - name: Setup service
      run: |
        sed -i 's+WORKSPACE_FOLDER+${{ github.workspace }}+' test/integration/self-hosted-notary/notary-service-container/server/server-deployment.yaml
        sed -i 's+WORKSPACE_FOLDER+${{ github.workspace }}+' test/integration/self-hosted-notary/notary-service-container/signer/signer-deployment.yaml
        kubectl apply -f test/integration/self-hosted-notary/notary-service-container/signer/signer-deployment.yaml --wait=true
        kubectl apply -f test/integration/self-hosted-notary/notary-service-container/signer/signer-service.yaml --wait=true
        kubectl apply -f test/integration/self-hosted-notary/notary-service-container/server/server-deployment.yaml --wait=true
        kubectl apply -f test/integration/self-hosted-notary/notary-service-container/server/server-service.yaml --wait=true
      shell: bash
    - name: Get IP
      id: get_service_ip
      run: |
        NOTARY_IP=$(kubectl get service notary-server -o jsonpath='{.spec.clusterIP}')
        echo service_ip=${NOTARY_IP} >> ${GITHUB_OUTPUT}
      shell: bash
