name: push

permissions: {}

on:
  push:
    branches:
      - master
      - develop

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/100_ci.yml
    permissions:
      packages: write
      contents: write
      security-events: write
    secrets: inherit
