name: release

permissions: {}

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: ./.github/workflows/101_build.yml
    permissions:
      packages: write
    secrets: inherit

  version-match:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Ensure version equality
        run: |
          IMAGE_TAG=${{ needs.build.outputs.original_tag }}
          for COMMIT_TAG in $(git tag --points-at $(git rev-parse HEAD)); do
            if [[ "$IMAGE_TAG" == "$COMMIT_TAG" ]]; then
              exit 0
            fi
          done
          echo "Tag '$IMAGE_TAG' is not within tags of commit: $(git tag --points-at $(git rev-parse HEAD))"
          exit 1

  integration-test:
    uses: ./.github/workflows/107_integration-test.yml
    needs: [build, version-match]
    permissions:
      packages: read
    secrets: inherit
    with:
      build_registry: ${{ needs.build.outputs.build_registry }}
      repo_owner: ${{ github.repository_owner }}
      build_image_repository: ${{ needs.build.outputs.build_registry }}/${{ needs.build.outputs.build_repo }}
      build_tag: ${{ needs.build.outputs.build_tag }}

  publish:
    uses: ./.github/workflows/200_publish.yml
    needs: [build, version-match, integration-test]
    permissions:
      contents: write
    with:
      chart_version: ${{ needs.build.outputs.chart_version }}
