name: unit-test

permissions: {}

on:
  workflow_call:
    inputs:
      jobs_to_run:
        description: "Which unit tests should be run: 'all', 'only-required', 'skip-all'?"
        type: string
        default: "all"

jobs:
  gotest:
    name: unit tests
    runs-on: ubuntu-latest
    if: inputs.jobs_to_run != 'skip-all'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: '1.22'
      - name: Test
        run: go test ./internal/... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
