name: sast

on:
  workflow_call:
    inputs:
      jobs_to_run:
        description: "Which sast jobs should be run: 'all', 'only-required', 'skip-all'?"
        type: string
        default: "all"
      output:
        description: 'Output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
        type: string
        required: false
        default: 'sarif'

permissions: {}

jobs:
  codeql:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all' &&
      inputs.output == 'sarif'
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        with:
          languages: 'go'
      - name: Analyze
        uses: github/codeql-action/analyze@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2

  golangci-lint:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run != 'skip-all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          cache: false
          go-version: '1.21'
      - name: Analyze cmd
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest
          args: '--timeout=10m --tests=false'
          working-directory: cmd
      - name: Analyze internal
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest
          args: '--timeout=10m --tests=false'
          working-directory: internal

  gosec:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run != 'skip-all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Analyze
        uses: securego/gosec@d2d3ae66bd8d340b78b5142b6fe610691783c2fe # v2.22.5
        with:
          args: "-exclude-dir=test -exclude-dir=tools ${{ inputs.output == 'sarif' && '-no-fail -fmt sarif -out gosec-results.sarif' || '-fmt text' }} ./..."
      - name: Upload
        uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'gosec-results.sarif'

  hadolint:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: build/Dockerfile
          format: ${{ inputs.output == 'sarif' && 'sarif' || 'tty' }}
          no-fail: ${{ inputs.output == 'sarif' && 'true' || 'false' }}
          output-file: ${{ inputs.output == 'sarif' && 'hadolint-results.sarif' || '' }}
      - name: Upload
        uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'hadolint-results.sarif'

  kubelinter:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Scan
        uses: stackrox/kube-linter-action@87802a2f4e01abebb3ee3c67a3002fea71f6eae5 # v1.0.7
        with:
          config: .github/.kube-linter/config.yaml
          directory: charts/connaisseur
          format: ${{ inputs.output == 'sarif' && 'sarif' || 'plain' }}
          output-file: ${{ inputs.output == 'sarif' && 'kubelinter-results.sarif' || 'kube-linter.log' }}
      - name: Upload
        uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'kubelinter-results.sarif'

  trivy-config-scan:
    name: trivy config
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Create reports folder
        run: |
          mkdir reports
        shell: bash
      - name: Render Helm charts
        run: |
          mkdir deployment
          helm template charts/connaisseur > deployment/deployment.yaml
        shell: bash
      - name: Scan deployment.yaml
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        with:
          scan-type: config
          scan-ref: deployment
          format: ${{ inputs.output }}
          output: ${{ inputs.output == 'sarif' && 'reports/trivy-k8s-results.sarif' || '' }}
      - name: Scan Dockerfiles
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        with:
          scan-type: config
          scan-ref: build
          format: ${{ inputs.output }}
          output: ${{ inputs.output == 'sarif' && 'reports/trivy-docker-results.sarif' || '' }}
      - name: Upload
        uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'reports'
